"use server";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { ENV_PATH, isConfigured, reloadEnv } from "../mcp";

type EnvMap = Record<string, string>;

function readEnvFile(): EnvMap {
  if (!existsSync(ENV_PATH)) return {};
  const raw = readFileSync(ENV_PATH, "utf8");
  const out: EnvMap = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function writeEnvFile(map: EnvMap): void {
  const header = "# ~/.ad-studio/.env — generated by Ad Studio setup wizard\n";
  const lines = Object.entries(map)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `${k}=${v}`);
  writeFileSync(ENV_PATH, header + lines.join("\n") + "\n", { mode: 0o600 });
}

export async function getSavedEnv(): Promise<{
  configured: boolean;
  has: Record<string, boolean>;
}> {
  const map = readEnvFile();
  const keys = [
    "GEMINI_API_KEY",
    "REPLICATE_API_TOKEN",
    "R2_ACCOUNT_ID",
    "R2_ACCESS_KEY_ID",
    "R2_SECRET_ACCESS_KEY",
    "R2_BUCKET",
    "R2_PUBLIC_BASE_URL",
  ] as const;
  const has: Record<string, boolean> = {};
  for (const k of keys) has[k] = Boolean(map[k]);
  return { configured: isConfigured(), has };
}

export async function saveEnvAction(patch: EnvMap): Promise<{ configured: boolean }> {
  const current = readEnvFile();
  const merged = { ...current, ...patch };
  writeEnvFile(merged);
  // Also push into the running process so subsequent requests see the new values.
  for (const [k, v] of Object.entries(patch)) process.env[k] = v;
  reloadEnv();
  return { configured: isConfigured() };
}

// --- Validators: light API calls that return ok/error ---

export async function validateGeminiKey(key: string): Promise<{ ok: boolean; error?: string }> {
  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(key)}`,
      { signal: AbortSignal.timeout(10_000) }
    );
    if (res.ok) return { ok: true };
    const body = await res.text();
    return { ok: false, error: `${res.status}: ${body.slice(0, 120)}` };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

export async function validateReplicateToken(token: string): Promise<{ ok: boolean; error?: string }> {
  try {
    const res = await fetch("https://api.replicate.com/v1/account", {
      headers: { Authorization: `Bearer ${token}` },
      signal: AbortSignal.timeout(10_000),
    });
    if (res.ok) return { ok: true };
    const body = await res.text();
    return { ok: false, error: `${res.status}: ${body.slice(0, 120)}` };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}
